//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SummonerSaveFileEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SummonerSaveFileEditor.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string characterNames {
            get {
                return ResourceManager.GetString("characterNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0	Gold	18	Gold	0	FALSE	
        ///1	Book of Masad	18	Gold	0	FALSE	
        ///2	Tablet of Masad	18	Gold	0	FALSE	
        ///3	Tome of Masad	18	Gold	0	FALSE	
        ///4	Book of Lenele	18	Gold	0	FALSE	
        ///5	Tablet of Lenele	18	Gold	0	FALSE	
        ///6	Tome of Lenele	18	Gold	0	FALSE	
        ///7	Book of Iona	18	Gold	0	FALSE	
        ///8	Tablet of Iona	18	Gold	0	FALSE	
        ///9	Tome of Iona	18	Gold	0	FALSE	
        ///10	Book of Khosani	18	Gold	0	FALSE	
        ///11	Tablet of Khosani	18	Gold	0	FALSE	
        ///12	Tome of Khosani	18	Gold	0	FALSE	
        ///13	Book of Ikaemos	18	Gold	0	FALSE	
        ///14	Tablet of Ikaemos	18	G [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string items {
            get {
                return ResourceManager.GetString("items", resourceCulture);
            }
        }
    }
}
